#!/bin/bash

# Generate PR-friendly clang-tidy report

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CPP_DIR="$(dirname "$SCRIPT_DIR")"

echo "Generating clang-tidy report for PR..."

cd "$CPP_DIR" || exit 1

# Run clang-tidy and generate structured output
find . -path "./build" -prune -o -path "./_deps" -prune -o \
    \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" \) -type f -print | \
    while IFS= read -r file; do
        echo "Analyzing: $file"

        # Run clang-tidy on individual file
        clang-tidy "$file" \
            --checks="-*,modernize-*,readability-*,performance-*,bugprone-*,-clang-diagnostic-error" \
            --extra-arg=-std=c++23 \
            --extra-arg=-I. \
            --format-style=file 2>&1 | \
            grep -E "^.*\.(cpp|hpp|h):[0-9]+:[0-9]+: warning:" | \
            while IFS= read -r warning; do
                echo "LINT_WARNING: $warning"
            done
    done > lint_warnings.txt

# Count warnings
WARNING_COUNT=$(grep -c "LINT_WARNING:" lint_warnings.txt || echo "0")

echo "Found $WARNING_COUNT warnings"

# Generate summary for PR
echo "## 🔍 Clang-tidy Analysis Results" > pr_lint_summary.md
echo "" >> pr_lint_summary.md

if [ "$WARNING_COUNT" -gt 0 ]; then
    echo "Found **$WARNING_COUNT** code style/quality issues:" >> pr_lint_summary.md
    echo "" >> pr_lint_summary.md
    echo "### Issues by File:" >> pr_lint_summary.md
    echo "" >> pr_lint_summary.md

    # Group warnings by file
    grep "LINT_WARNING:" lint_warnings.txt | sed 's/LINT_WARNING: //' | \
        cut -d: -f1 | sort | uniq -c | \
        while read count file; do
            echo "- **$file**: $count issue(s)" >> pr_lint_summary.md
        done

    echo "" >> pr_lint_summary.md
    echo "### Sample Issues:" >> pr_lint_summary.md
    echo "" >> pr_lint_summary.md

    # Show first few warnings
    grep "LINT_WARNING:" lint_warnings.txt | sed 's/LINT_WARNING: //' | head -5 | \
        while IFS= read -r warning; do
            echo "- \`$warning\`" >> pr_lint_summary.md
        done

    if [ "$WARNING_COUNT" -gt 5 ]; then
        echo "- ... and $((WARNING_COUNT - 5)) more issues" >> pr_lint_summary.md
    fi

    echo "" >> pr_lint_summary.md
    echo "💡 **Suggestion**: Review the CI logs for detailed information and consider addressing these issues to improve code quality." >> pr_lint_summary.md
else
    echo "🎉 **Great job!** No code style or quality issues found." >> pr_lint_summary.md
fi

echo "" >> pr_lint_summary.md
echo "---" >> pr_lint_summary.md
echo "*This comment was automatically generated by clang-tidy CI check.*" >> pr_lint_summary.md

echo "Report generated: pr_lint_summary.md"
